package source;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alunocmc
 */
public class FormDados extends javax.swing.JFrame {

        ControleCalcFinan controle = new ControleCalcFinan();
        
        
    /**
     * Creates new form FormNota
     */
    public FormDados() {
        controle.Conexao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFinan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textNumParc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textJuros = new javax.swing.JTextField();
        butCadastrar = new javax.swing.JButton();
        butListar = new javax.swing.JButton();
        butConsultar = new javax.swing.JButton();
        butAlterar = new javax.swing.JButton();
        butSair = new javax.swing.JButton();
        textNotasAlunos = new javax.swing.JLabel();
        butExcluir = new javax.swing.JButton();
        ButCalcFinanSAC = new javax.swing.JButton();
        ButLimpaCampo = new javax.swing.JButton();
        textIdFinan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ButCalcFinanPRICE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID do Financiamento");

        textFinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFinanActionPerformed(evt);
            }
        });

        jLabel2.setText("Número de Parcelas");

        textNumParc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumParcActionPerformed(evt);
            }
        });

        jLabel3.setText("Taxa de Juros");

        textJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJurosActionPerformed(evt);
            }
        });

        butCadastrar.setText("Cadastrar");
        butCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCadastrarActionPerformed(evt);
            }
        });

        butListar.setText("Listar");
        butListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butListarActionPerformed(evt);
            }
        });

        butConsultar.setText("Consultar");
        butConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConsultarActionPerformed(evt);
            }
        });

        butAlterar.setText("Alterar");
        butAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAlterarActionPerformed(evt);
            }
        });

        butSair.setText("Sair");
        butSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSairActionPerformed(evt);
            }
        });

        textNotasAlunos.setText("Cálculo de Financiamento");

        butExcluir.setText("Excluir");
        butExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExcluirActionPerformed(evt);
            }
        });

        ButCalcFinanSAC.setText("Calcular Financiamento com SAC");
        ButCalcFinanSAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCalcFinanSACActionPerformed(evt);
            }
        });

        ButLimpaCampo.setText("Limpar Campos");
        ButLimpaCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLimpaCampoActionPerformed(evt);
            }
        });

        textIdFinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdFinanActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor do Financiamento ");

        ButCalcFinanPRICE.setText("Calcular Financiamento com PRICE");
        ButCalcFinanPRICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCalcFinanPRICEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(textIdFinan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)
                                .addComponent(textNumParc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(textFinan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(77, 77, 77)
                                .addComponent(textJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButCalcFinanPRICE)
                            .addComponent(ButCalcFinanSAC, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(butAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butCadastrar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(butListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(butConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(ButLimpaCampo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(textNotasAlunos)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(textNotasAlunos)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(ButCalcFinanSAC)
                                .addGap(37, 37, 37)
                                .addComponent(ButCalcFinanPRICE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textIdFinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textNumParc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butCadastrar)
                            .addComponent(butListar)
                            .addComponent(butConsultar))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButLimpaCampo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAlterar)
                    .addComponent(butSair)
                    .addComponent(butExcluir))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFinanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFinanActionPerformed

    private void textJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJurosActionPerformed

    private void butListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butListarActionPerformed
        controle.Listar();
    }//GEN-LAST:event_butListarActionPerformed

    private void butAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAlterarActionPerformed
        try{
            controle.Alterar(Integer.parseInt(this.textIdFinan.getText()), Double.parseDouble(this.textFinan.getText()), 
            Integer.parseInt(this.textNumParc.getText()), Double.parseDouble(this.textJuros.getText()));
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Digite o ID de financiamento que deseja alterar. "
                    + "Então, preencha todos os campos com números");
        }
        this.textIdFinan.setText("");
        this.textFinan.setText("");
        this.textNumParc.setText("");
        this.textJuros.setText("");
    }//GEN-LAST:event_butAlterarActionPerformed

    private void butSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butSairActionPerformed

    private void butCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCadastrarActionPerformed
        try{
            controle.Cadastrar(
                    Integer.parseInt(this.textIdFinan.getText()),
                    Double.parseDouble(this.textFinan.getText()), 
                    Integer.parseInt(this.textNumParc.getText()), 
                    Double.parseDouble(this.textJuros.getText()));
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos com números");
        } 
        
        this.textIdFinan.setText("");
        this.textFinan.setText("");
        this.textNumParc.setText("");
        this.textJuros.setText("");       
    }//GEN-LAST:event_butCadastrarActionPerformed

    private void butConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConsultarActionPerformed
        try{
            String consulta = controle.Consultar(Integer.parseInt(this.textIdFinan.getText()));
            String vet[] = consulta.split(";");
            this.textFinan.setText(vet[0]);
            this.textNumParc.setText(vet[1]);
            this.textJuros.setText(vet[2]);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Preencha o campo de 'ID do Financiamento' para consultar um financiamento!");
        }
    }//GEN-LAST:event_butConsultarActionPerformed

    private void butExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExcluirActionPerformed
            try {
                controle.Excluir(Integer.parseInt(this.textIdFinan.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(FormDados.class.getName()).log(Level.SEVERE, null, ex);
            } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Preencha o campo de ID de financiamento!");
            }
        this.textIdFinan.setText("");   
    }//GEN-LAST:event_butExcluirActionPerformed

    private void ButLimpaCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLimpaCampoActionPerformed
        this.textIdFinan.setText("");
        this.textFinan.setText("");
        this.textNumParc.setText("");
        this.textJuros.setText("");
    }//GEN-LAST:event_ButLimpaCampoActionPerformed

    private void ButCalcFinanSACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCalcFinanSACActionPerformed
        try{
            this.textFinan.setText(""+controle.CalcularSAC(Double.parseDouble(this.textFinan.getText()),
            Integer.parseInt(this.textNumParc.getText()), Double.parseDouble(this.textJuros.getText())));
        } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos com números");
        }
        this.textIdFinan.setText("");
        this.textFinan.setText("");
        this.textNumParc.setText("");
        this.textJuros.setText("");
    }//GEN-LAST:event_ButCalcFinanSACActionPerformed

    private void textNumParcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumParcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumParcActionPerformed

    private void textIdFinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdFinanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdFinanActionPerformed

    private void ButCalcFinanPRICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCalcFinanPRICEActionPerformed
        try{   
            this.textFinan.setText(""+controle.CalcularPRICE(Double.parseDouble(this.textFinan.getText()),
            Integer.parseInt(this.textNumParc.getText()), Double.parseDouble(this.textJuros.getText())));
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos com números");
        }
        this.textIdFinan.setText("");
        this.textFinan.setText("");
        this.textNumParc.setText("");
        this.textJuros.setText("");
    }//GEN-LAST:event_ButCalcFinanPRICEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            //</editor-fold>
            
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormDados().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButCalcFinanPRICE;
    private javax.swing.JButton ButCalcFinanSAC;
    private javax.swing.JButton ButLimpaCampo;
    private javax.swing.JButton butAlterar;
    private javax.swing.JButton butCadastrar;
    private javax.swing.JButton butConsultar;
    private javax.swing.JButton butExcluir;
    private javax.swing.JButton butListar;
    private javax.swing.JButton butSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textFinan;
    private javax.swing.JTextField textIdFinan;
    private javax.swing.JTextField textJuros;
    private javax.swing.JLabel textNotasAlunos;
    private javax.swing.JTextField textNumParc;
    // End of variables declaration//GEN-END:variables
}
